In [1]:
# Проверка версии, либо pip show pandas в терминале

import pandas as pd
import numpy as np

print(pd.__version__)
print(pd.show_versions(as_json=True))

2.2.2
{
  "system": {
    "commit": "d9cdd2ee5a58015ef6f4d15c7226110c9aab8140",
    "python": "3.12.5.final.0",
    "python-bits": 64,
    "OS": "Windows",
    "OS-release": "10",
    "Version": "10.0.19045",
    "machine": "AMD64",
    "processor": "AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD",
    "byteorder": "little",
    "LC_ALL": null,
    "LANG": null,
    "LOCALE": {
      "language-code": "Russian_Russia",
      "encoding": "1251"
    }
  },
  "dependencies": {
    "pandas": "2.2.2",
    "numpy": "2.1.0",
    "pytz": "2024.1",
    "dateutil": "2.9.0.post0",
    "setuptools": "74.0.0",
    "pip": "26.1.2",
    "Cython": null,
    "pytest": null,
    "hypothesis": null,
    "sphinx": null,
    "blosc": null,
    "feather": null,
    "xlsxwriter": null,
    "lxml.etree": "6.1.1",
    "html5lib": "1.1",
    "pymysql": null,
    "psycopg2": null,
    "jinja2": "3.1.6",
    "IPython": "9.2.0",
    "pandas_datareader": null,
    "adbc-driver-postgresql": null,
    "adbc-driver-sqlite": null,
    "bs4": "4.15.0",
    "bottleneck": null,
    "dataframe-api-compat": null,
    "fastparquet": null,
    "fsspec": null,
    "gcsfs": null,
    "matplotlib": null,
    "numba": null,
    "numexpr": null,
    "odfpy": null,
    "openpyxl": "3.1.5",
    "pandas_gbq": null,
    "pyarrow": null,
    "pyreadstat": null,
    "python-calamine": null,
    "pyxlsb": null,
    "s3fs": null,
    "scipy": "1.18.0",
    "sqlalchemy": "2.0.51",
    "tables": null,
    "tabulate": null,
    "xarray": null,
    "xlrd": "2.0.2",
    "zstandard": null,
    "tzdata": "2024.1",
    "qtpy": null,
    "pyqt5": null
  }
}None

In [7]:
# Преобазование списка, массива numpy и словаря в объект Series

import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

mylist_p=pd.Series(mylist)
myarr_p=pd.Series(myarr)
mydict_p=pd.Series(mydict)

type(mylist_p), type(myarr_p), type(mydict_p)

(pandas.core.series.Series,
 pandas.core.series.Series,
 pandas.core.series.Series)

In [10]:
# Создание датафрейма из разных структур данных

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df=pd.DataFrame({'col1': ser1, 'col2': ser2}) # или df=pd.concat([ser1, ser2], axis=1)
df.head()

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [12]:
# Изменение имени серии

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [17]:
# Фильтрация значений в Series с помощью маски

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Метод isin() проверяет, есть ли каждый элемент ser1 внутри ser2. Он возвращает булеву маску 
# ~ отрицает True условие
res=ser1[~ser1.isin(ser2)]
res

0    1
1    2
2    3
dtype: int64

In [9]:
# Нахождение симметрической разницы
# Тоже самое, что ниже, но короче 
# pd.Series(np.setxor1d(ser1, ser2))

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# np.union1d(ser1, ser2) - Объединение
# Она берет два массива, объединяет их и убирает дубликаты, возвращая отсортированный массив уникальных значений.
ser_u = pd.Series(np.union1d(ser1, ser2))  # union

# np.intersect1d(ser1, ser2) — Пересечение
# Возвращает только те элементы, которые есть в обоих массивах одновременно (тоже отсортированные и уникальные).
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
print(ser_i)

# Отрицание маски
ser_u[~ser_u.isin(ser_i)]

0    4
1    5
dtype: int64

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [29]:
# Базовая статистика через метод numpy и через метод pandas
# Один проход по массиву, очень быстро

state = np.random.default_rng(100)
ser = pd.Series(state.normal(10, 5, size=25))

res1=np.percentile(ser, q=[0, 25, 50, 75, 100])
res2=ser.quantile([0, 0.25, 0.50, 0.75, 1.0])

res1,res2

(array([ 0.34449292,  6.55441142, 11.44877901, 13.72531301, 21.21486198]),
 0.00     0.344493
 0.25     6.554411
 0.50    11.448779
 0.75    13.725313
 1.00    21.214862
 dtype: float64)

In [18]:
# value_counts() подсчет количества уникальных элементов в серии
# Аналог collecions.Counter, но возвращает не словарь, а Series

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

b    7
a    6
e    4
g    4
f    3
c    3
d    2
h    1
Name: count, dtype: int64

In [ ]:
# Создаем генератор с фиксированным зерном
rng = np.random.default_rng(100)

# Используем его метод integers вместо randint
ser = pd.Series(rng.integers(1, 5, size=12))

# Находим два самых частых значения
top2 = ser.value_counts().head(2).index
print(top2)

# Оставляем их, остальное заменяем на "Другое"
result = ser.where(ser.isin(top2), 'Другое')

# Либо так:
# result = pd.Series(np.where(ser.isin(top2), ser, 'Другое'))

# Либо так:
# result = ser.mask(~ser.isin(top2), 'Другое')

print(result)

Index([4, 1], dtype='int64')
0          4
1          4
2          1
3     Другое
4          1
5     Другое
6     Другое
7          1
8     Другое
9          4
10         4
11    Другое
dtype: object

In [38]:
# Децили (Deciles)
# Определение: Делят данные на 10 равных частей по количеству наблюдений. Каждый дециль содержит ~10% данных.

# Квартили (Quartiles)
# Определение: Делят данные на 4 равные части. Каждый квартиль содержит ~25% данных.

# Процентили (Percentiles)
# Определение: Делят данные на 100 равных частей. Каждый процентиль содержит ~1% данных.

In [37]:
# Децили — это квантили, которые делят данные на 10 равных частей по количеству наблюдений. 
# То есть в каждом дециле будет примерно одинаковое число элементов (в нашем случае: 20 / 10 = по 2 элемента в каждом дециле).

ser = pd.Series(np.random.random(20))

# Разбиваем на 10 децилей с именованными метками
# q=10 — на сколько частей разбить (10 децилей)
# Делит на группы с одинаковым количеством элементов
result = pd.qcut(ser, q=10, labels=[f'D{i}' for i in range(1, 11)])

# Делит на группы с одинаковой шириной интервала
result2= pd.cut(ser, bins=10).value_counts()

print(result)
print(result2)

0      D1
1      D9
2      D5
3      D4
4      D6
5      D7
6      D2
7      D2
8      D7
9      D9
10     D4
11    D10
12     D8
13     D1
14    D10
15     D5
16     D3
17     D3
18     D6
19     D8
dtype: category
Categories (10, object): ['D1' < 'D2' < 'D3' < 'D4' ... 'D7' < 'D8' < 'D9' < 'D10']
(0.315, 0.413]    5
(0.02, 0.119]     4
(0.51, 0.608]     4
(0.902, 1.0]      2
(0.119, 0.217]    1
(0.217, 0.315]    1
(0.413, 0.51]     1
(0.608, 0.706]    1
(0.706, 0.804]    1
(0.804, 0.902]    0
Name: count, dtype: int64

In [5]:
# Преобразование Series в датафрейм заданного размера

ser = pd.Series(np.random.randint(1, 10, 35))
df=pd.DataFrame(ser.values.reshape(7,5))
df

   0  1  2  3  4
0  2  3  3  1  8
1  7  1  2  4  7
2  5  7  3  5  7
3  4  6  8  4  8
4  8  2  1  2  4
5  2  6  8  3  3
6  4  2  2  8  5

In [101]:
# Загрузка только нужных строк в датафрейм
# df = pd.read_csv('data.csv', usecols=['Name', 'Age', 'City'])
# df = pd.read_csv('data.csv', usecols=[0, 2, 4])

# Загружаем каждую n строку файла в датафрейм
# df = pd.read_csv('data.csv', skiprows=lambda x: x % 3 != 0)

# # Все столбцы, кроме 'password'
# df = pd.read_csv('users.csv', usecols=lambda x: x != 'password')

# # Все столбцы с 'date' или 'price' в названии
# df = pd.read_csv('sales.csv', usecols=lambda x: 'date' in x.lower() or 'price' in x.lower())

# df = pd.read_csv(
#    'data.csv',
#    usecols=['id', 'name', 'value'],  # только эти столбцы
#    nrows=1000,                        # только первые 1000 строк
#    dtype={'id': int, 'value': float}  # типы данных
# )

# Изменение импортируемых значений во время импорта, а не изменение датафрейма после
# df = pd.read_csv('users.csv', converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})

# # Безопасная загрузка: пропускаем отсутствующие столбцы
# try:
#    df = pd.read_csv('data.csv', usecols=['A', 'B', 'C'])
# except ValueError as e:
#     print(f"Некоторые столбцы отсутствуют: {e}")
#     # Загружаем только существующие
#     df = pd.read_csv('data.csv', usecols=['A', 'B'])


# chunksize для больших файлов, которые не помещаются в память
# chunks = pd.read_csv('huge.csv', chunksize=10000)
# result = pd.concat([chunk.iloc[::3] for chunk in chunks])

# Загружаем каждую n строку файла в датафрейм
# df = pd.read_csv('data.csv', skiprows=lambda x: x % 3 != 0)


# chunksize для больших файлов, которые не помещаются в память
# chunks = pd.read_csv('huge.csv', chunksize=10000)
# result = pd.concat([chunk.iloc[::3] for chunk in chunks])

In [45]:
# Поиск индексов в Series по какому-то условию

ser = pd.Series(np.random.randint(1, 10, 7))
res=np.argwhere(ser%3==0)
res

array([[1],
       [4],
       [6]])

In [61]:
# Извлечение элементов Series по индексам из списка

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [84]:
# Вертикальное и горизонтальное объединение Series в датафрейм

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))


df=pd.concat([ser1,ser2], axis=1, keys=['numbers', 'letters'])
df2=pd.concat([ser1,ser2], axis=0)

df,df2

(   numbers letters
 0        0       a
 1        1       b
 2        2       c
 3        3       d
 4        4       e,
 0    0
 1    1
 2    2
 3    3
 4    4
 0    a
 1    b
 2    c
 3    d
 4    e
 dtype: object)

In [100]:
# Поиск индекса элемента ser2 в ser1 с сохранением порядка как в ser2
# get_loc ищет индекс по значению в pd.index(ser1)

ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

res=[pd.Index(ser1).get_loc(el) for el in ser2]
res

[5, 4, 0, 8]

In [101]:
# MSE (Mean Squared Error) — это метрика, которая показывает, насколько сильно предсказания отличаются от реальных значений.
# Среднее значение квадратов разностей между истиной и предсказанием 
# Чем меньше MSE, тем точнее предсказания.


truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Способ 1: вручную (по формуле)
mse = ((truth - pred) ** 2).mean()
print(f"MSE: {mse:.4f}")

# Способ 2: через sklearn (профессиональный)
from sklearn.metrics import mean_squared_error
mse_sklearn = mean_squared_error(truth, pred)
print(f"MSE (sklearn): {mse_sklearn:.4f}")

MSE: 0.2641
MSE (sklearn): 0.2641

In [111]:
# Каждая буква элемента Series заглавная

er = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.str.capitalize() # или ser.str.title()

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [118]:
# Подсчет количества элементов каждом слове

ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [123]:
# Вычисление разницы между соседними элементами
# diff() автоматически подставляет предыдущий элемент

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
stage1=ser.diff()
res=stage1.diff() # или ser.diff().diff()
print(stage1)
print(res)

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64
0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64

In [128]:
# Преобразование любого формата даты в datetime64
# format='mixed' для каждого элемента свой шаблон
# dayfirst=True Интерпретирует 02-03-2011 как 2 марта (европейский стиль)

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
res=pd.to_datetime(ser, format='mixed', dayfirst=True)
res

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [138]:
# После преобразования в datetime, можно использовать методы dt, чтобы выташить и отформатировать дату как захочется

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

datetimes=pd.to_datetime(ser, format='mixed', dayfirst=True)

days=datetimes.dt.day.to_list()
weeks=datetimes.dt.isocalendar().week.to_list()
day_nums=datetimes.dt.day_of_year.to_list()
days_of_week=datetimes.dt.day_name().to_list()

print(days)
print(weeks)
print(day_nums)
print(days_of_week)

[1, 2, 3, 4, 5, 6]
[53, 5, 9, 14, 19, 23]
[1, 33, 63, 94, 125, 157]
['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

In [150]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
datetimes = pd.to_datetime(ser, format='%b %Y')  # убираем предупреждение

# Добавляем к datetime64 какой-то период через pd.to_timedelta
result = datetimes + pd.to_timedelta(3, unit='D')

print(result)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [2]:
# Регулярное выражение [aeiouAEIOU] означает "любая гласная буква (строчная или заглавная)". 
# Метод count() считает количество совпадений в каждом слове

ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

res = ser[ser.str.count('[aeiouAEIOU]') >= 2]
res

0     Apple
1    Orange
4     Money
dtype: object

In [16]:
# Фильтрация Series по регуляркам

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

# Извлекаем email (возвращает DataFrame с одной колонкой)
result = emails.str.extract(f'({pattern})', expand=False).dropna()

# Лмбо через маску
# mask = emails.str.contains(pattern, regex=True)
# result = emails[mask]




result

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [29]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

df=pd.DataFrame({'fruit': fruit, 'weights': weights})
res=df.groupby('fruit')['weights'].mean().round(1)

# Или сразу weights.groupby(fruit).mean().round(1)
res

fruit
apple     6.3
banana    6.3
carrot    4.2
Name: weights, dtype: float64

In [37]:
# Вычисление евклидова расстояния
# Арифметические операции между Series автоматически происходят между элементами 

import math

p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

res=sum((p - q)**2)**.5
res

18.16590212458495

In [41]:
# Нахождение пиков в Series

ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# Сравниваем каждый элемент с соседями
# shift(1) — сдвиг на 1 вправо (это "сосед слева")
# shift(-1) — сдвиг на 1 влево (это "сосед справа")
peak_mask = (ser > ser.shift(1)) & (ser > ser.shift(-1))

# Получаем индексы пиков
peak_indices = ser[peak_mask].index.tolist()
print("Индексы пиков:", peak_indices)


# Получаем значения пиков
peak_values = ser[peak_mask].tolist()
print("Значения пиков:", peak_values)

Индексы пиков: [1, 5, 7]
Значения пиков: [10, 10, 7]

In [6]:
# Замена символа на наиболее часто встречающийся в Series

my_str = 'dbc deb abed gade'
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()

least_freq = freq.dropna().index[-1]
print(least_freq)

res=my_str.replace(' ',least_freq)

# или res="".join(ser.replace(' ', least_freq))

res

g

'dbcgdebgabedggade'

In [13]:
# Создание временного ряда начиная с определенной даты 10 суббот
# Приклеивание к каждой дате рандомного числа
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    7
2000-01-08    9
2000-01-15    7
2000-01-22    2
2000-01-29    2
2000-02-05    3
2000-02-12    4
2000-02-19    8
2000-02-26    6
2000-03-04    7
Freq: W-SAT, dtype: int32

In [18]:
# Заполнение пропущенных значений временного ряда следующим значением и reindex маски

ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
# Сохраняем маску исходных NaN
original_nan_mask = ser.isna()

# Создаём полный индекс и заполняем
result = ser.asfreq('D').ffill()

# Возвращаем NaN на исходные позиции
result[original_nan_mask.reindex(result.index, fill_value=False)] = np.nan
result

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [8]:
# Автокорреляция — это мера того, насколько значения ряда связаны с его же значениями, но сдвинутыми на k позиций (лаг k).
# Простыми словами: "Насколько сегодняшнее значение похоже на значение k дней назад?"

ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Вычисляем автокорреляции для лагов 1-10
# Встроенный метод pandas autocorr, который считает корреляцию Пирсона между рядом и его сдвинутой версией
autocorr = [ser.autocorr(lag=i) for i in range(1, 11)]

for i, corr in enumerate(autocorr, start=1):
    print(f" {i:2d} | {corr:.4f}")

# Находим индекс максимального значения и добавляем 1 (т.к. нумерация лагов с 1)
max_lag = np.argmax(autocorr) + 1 
max_corr = max(autocorr)
print(f"\nНаибольшая автокорреляция: {max_corr:.4f} при лаге {max_lag}")

  1 | 0.2162
  2 | 0.3873
  3 | 0.4317
  4 | -0.0854
  5 | 0.0398
  6 | 0.1691
  7 | -0.4360
  8 | 0.4139
  9 | -0.0295
 10 | -0.1554

Наибольшая автокорреляция: 0.4317 при лаге 3

In [12]:
# Загружаем каждую n строку файла в датафрейм
# df = pd.read_csv('data.csv', skiprows=lambda x: x % 3 != 0)


# chunksize для больших файлов, которые не помещаются в память
# chunks = pd.read_csv('huge.csv', chunksize=10000)
# result = pd.concat([chunk.iloc[::3] for chunk in chunks])

In [16]:
df=pd.DataFrame({'col1':[10,10,26,26,26,10,12]})

# np.where(условие, значение_если_True, значение_если_False)
df['col1'] = np.where(df['col1'] < 25, 'Маленькие', 'Высокие')

# Для сложныых условий, применение apply(func) к каждой строке
# def categorize(val):
#    return 'Маленькие' if val < 25 else 'Высокие'
# df['col1'] = df['col1'].apply(categorize)

df

        col1
0  Маленькие
1  Маленькие
2    Высокие
3    Высокие
4    Высокие
5  Маленькие
6  Маленькие

In [47]:
# Нарезка Series на окна — это способ превратить временной ряд в таблицу для машинного обучения.
# Такая нарезка — это фундаментальный приём в анализе временных рядов и машинном обучении. Вот основные применения:
#  предсказать следующее значение по предыдущим 4
# Анализ текста (NLP) Окна по словам — это n-граммы для анализа текста:


L = pd.Series(range(15))
window_size = 4
step = 2

# Через sliding_window_view с шагом
windows = np.lib.stride_tricks.sliding_window_view(L.values, window_size)[::step]
print(windows)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]

In [69]:
base = "https://python-academy.org/static/product-analytics/dataset"


# parse_dates преобразует столбцы в тип даты для датафрейма
users = pd.read_csv(f"{base}/users.csv", parse_dates=["signup_date"])

# Сколько столбцов какого-типа
print(users.dtypes.value_counts())

# Структура всего датафрейма
print(users.info())

df_np=users.to_numpy()
print(df_np[::5])

df_lst=users.to_numpy().tolist()
print(df_lst[::5])

object            5
datetime64[ns]    1
bool              1
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           6000 non-null   object
 1   signup_date       6000 non-null   datetime64[ns]
 2   source            6000 non-null   object
 3   country           6000 non-null   object
 4   device_first      6000 non-null   object
 5   age_bucket        5691 non-null   object
 6   marketing_opt_in  6000 non-null   bool
dtypes: bool(1), datetime64[ns](1), object(5)
memory usage: 287.2+ KB
None
[['u_00001' Timestamp('2026-04-04 00:00:00') 'paid_social' ... 'mobile'
  '35-44' False]
 ['u_00006' Timestamp('2026-05-25 00:00:00') 'paid_social' ... 'tablet'
  '25-34' False]
 ['u_00011' Timestamp('2025-11-25 00:00:00') 'paid_search' ... 'mobile'
  '55+' False]
 ...
 ['u_05986' Timestamp('2025-11-24 00:00:00') 'paid_social' ... 'mobile'
  '18-24' True]
 ['u_05991' Timestamp('2025-08-07 00:00:00') 'email' ... 'mobile' nan
  True]
 ['u_05996' Timestamp('2025-11-27 00:00:00') 'referral' ... 'mobile'
  '35-44' False]]

In [119]:
# Нахождение индексов колонки и строки для конкретной ячейки в датафрейме

users2=users.loc[users.signup_date == users.signup_date.max(), ['user_id', 'country', 'age_bucket']]
# Или через query
# users2 = users.query("signup_date == @users.signup_date.max() and age_bucket == '55+'")[['user_id', 'country', 'age_bucket']]



# Ищем ячейки, где age_bucket == '55+' во ВСЁМ DataFrame users2
mask = (users2== '55+').values  # 2D массив!
print(users2[mask])

rows, cols = np.where(mask)

print("Строки:", rows)
print("Колонки:", cols)


# Получить значение ячейки
print("Значение:", users2.iat[rows[0], cols[0]])
print('Метка pandas из изначального датафрейма', users2.index[rows[0]])

      user_id country age_bucket
5045  u_05046      AM        55+
Строки: [26]
Колонки: [2]
Значение: 55+
Метка pandas из изначального датафрейма 5045

In [2]:
# Способы переименовать колонки датафрейма

df=pd.DataFrame({'col.1':[1,2],'col.2':[3,4], 'type':[5,6]})
df2=df.copy()
df.columns = df.columns.str.replace('.', '_', regex=False)
df2.columns = [col.replace('.', '_') if col!='type' else col=='type2' for col in df2.columns]
df, df2

(   col_1  col_2  type
 0      1      3     5
 1      2      4     6,
    col_1  col_2  False
 0      1      3      5
 1      2      4      6)

In [7]:
# Проверка количества пустых значений в каждой колонке

df=pd.DataFrame({'col.1':[1,None],'col.2':[3,4]})
df.isna().sum()

col.1    1
col.2    0
dtype: int64

In [11]:
# Нахождение имени колонки с максимальны значние пустых значений

df=pd.DataFrame({'col.1':[1,None],'col.2':[3,4]})

m=df.isna().sum().idxmax()
m

'col.1'

In [30]:
# Заполнение пустых значений в столбце результатом какой-то формулы
# NB! np.nan==np.nan всегда False, поэтому в качестве проверки лучше использовать .isna()

df=pd.DataFrame({'col1':[1,2,3,np.nan,50,np.nan],'col2':[3,4, np.nan, np.nan,10,20]})
print(df['col1'].mean())
print(df['col2'].median())
df['col1']=np.where(df['col1'].isna(),df['col1'].mean(),df['col1'])
df['col2']=np.where(df['col2'].isna(),df['col2'].median(),df['col2'])
df

14.0
7.0

   col1  col2
0   1.0   3.0
1   2.0   4.0
2   3.0   7.0
3  14.0   7.0
4  50.0  10.0
5  14.0  20.0

In [2]:
# Вариант со словарем, если нужно обрабатывать множество колонок

# Еще более простой и лаконичный способ для pandas
# df.fillna({
#    'col1': df['col1'].mean(),
#    'col2': df['col2'].median()
# }, inplace=True)

df=pd.DataFrame({'col1':[1,2,3,np.nan,50,np.nan],'col2':[3,4, np.nan, np.nan,10,20]})
print(df['col1'].mean())
print(df['col2'].median())

# ✅ Синтаксис pandas через lambda
dict_func = {
    'col1': lambda x: x.mean(),
    'col2': lambda x: x.median()
}

df[list(dict_func.keys())] = df[list(dict_func.keys())].apply(
    lambda x, d: x.fillna(d[x.name](x)), args=(dict_func,)
)
df

14.0
7.0

   col1  col2
0   1.0   3.0
1   2.0   4.0
2   3.0   7.0
3  14.0   7.0
4  50.0  10.0
5  14.0  20.0

In [6]:
# Преобразование столбца датафрейма в отдельный датафрейм

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df_a=df['a'].to_frame(name='df_a')
df_a

   df_a
0     0
1     5
2    10
3    15

In [9]:
# Сортировка столбцов в датафрейме

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df_sorted = df[sorted(df.columns, reverse=True)]

# Или через reindex (альтернатива)
# df_sorted = df.reindex(sorted(df.columns, reverse=True), axis=1)

df_sorted

    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

In [12]:
# Универсальная функция обмена столбцов


df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

print(df)


def swap_columns(df, col1, col2):
    """Меняет местами два столбца по их именам."""
    col_list = list(df.columns)
    # Находим позиции столбцов
    idx1, idx2 = col_list.index(col1), col_list.index(col2)
    # Меняем местами
    col_list[idx1], col_list[idx2] = col_list[idx2], col_list[idx1]
    # Возвращаем DataFrame с новым порядком колонок
    return df[col_list]

# Пример использования: меняем 'a' и 'd'
df_swapped = swap_columns(df, 'a', 'd')
print('После замены')
print(df_swapped)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
После замены
    d   b   c   a   e
0   3   1   2   0   4
1   8   6   7   5   9
2  13  11  12  10  14
3  18  16  17  15  19

In [26]:
# Все опции вывода

# display.max_rows
# Макс. строк при печати

# display.max_columns
# Макс. столбцов при печати

# display.min_rows
# Мин. строк при усечении

# display.width
# Ширина окна (в символах)

# display.max_colwidth
# Макс. ширина содержимого ячейки

# display.precision
# Точность чисел с плавающей точкой

# display.float_format
# Формат вывода float

# Сброс настроек
# pd.reset_option('^display.')

df = pd.DataFrame(np.arange(100).reshape(-1, 4))


# Устанавливаем лимиты
pd.set_option('display.max_rows', 10)       # максимум 10 строк
pd.set_option('display.max_columns', 2)    # максимум 2 столбца

# Проверяем
print(pd.get_option('display.max_rows')) 
print(pd.get_option('display.max_columns'))


print(df)

10
2
     0  ...   3
0    0  ...   3
1    4  ...   7
2    8  ...  11
3   12  ...  15
4   16  ...  19
..  ..  ...  ..
20  80  ...  83
21  84  ...  87
22  88  ...  91
23  92  ...  95
24  96  ...  99

[25 rows x 4 columns]

In [24]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Устанавливаем формат
pd.set_option('display.float_format', '{:.4f}'.format)       # максимум 10 строк

# Проверяем
print(pd.get_option('display.float_format'))

print(df)

<built-in method format of str object at 0x000001B0334CF270>
   random
0  0.6699
1  0.0001
2  0.0653
3  0.0001

In [27]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Устанавливаем формат
pd.set_option('display.float_format', '{:.2%}'.format)       # максимум 10 строк

# Проверяем
print(pd.get_option('display.float_format'))

print(df)

<built-in method format of str object at 0x000001B034BBAD60>
   random
0  84.39%
1  36.00%
2  95.41%
3   8.36%

In [33]:
# Фильтрация строк в датафрейме, каждая четвертая строка

df=pd.DataFrame(np.arange(20), columns=['col'])
df=df[df['col']%4==0]
df

    col
0     0
4     4
8     8
12   12
16   16

In [41]:
# Пример создания уникального индекс (первичного ключа) в датафрейме


pd.reset_option('^display.')
df=pd.DataFrame({'Manufacturer':['Acura',None, 'Audi', 'Audi', 'BMW'], 'Model':['Integra','Legend', '90', '100', '535'], 'Type':['Small','Midsize', 'Compact', 'Midsize', 'Midsize']})
df['Manufacturer'] = df['Manufacturer'].fillna('missing')
df.index = df['Manufacturer'] + '_' + df['Model'] + '_' + df['Type']
df

                       Manufacturer    Model     Type
Acura_Integra_Small           Acura  Integra    Small
missing_Legend_Midsize      missing   Legend  Midsize
Audi_90_Compact                Audi       90  Compact
Audi_100_Midsize               Audi      100  Midsize
BMW_535_Midsize                 BMW      535  Midsize